### ISSUE TITLE
can't build ui

### ISSUE THREAD

**Issue by sexy-yume** [FSoft-AI4Code/AgileCoder#17]
C:\Users\hbw33\AgileCoder\ui>C:\Users\hbw33\AgileCoder\ui\agilecoder_ui.py
24.11.04 01:01:13: root: INFO   : Initializing Devika...
24.11.04 01:01:13: root: INFO   : Initializing Prerequisites Jobs...
Traceback (most recent call last):
  File "C:\Users\hbw33\AgileCoder\ui\agilecoder_ui.py", line 24, in <module>
    from src.agents import Agent
  File "C:\Users\hbw33\AgileCoder\ui\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "C:\Users\hbw33\AgileCoder\ui\src\agents\agent.py", line 18, in <module>
    from agilecoder.camel.typing import ModelType
  File "c:\users\hbw33\agilecoder\ui\src\agilecoder\agilecoder\__init__.py", line 1, in <module>
    from .cli import main
  File "c:\users\hbw33\agilecoder\ui\src\agilecoder\agilecoder\cli.py", line 3, in <module>
    from agilecoder.run_api import run_task
  File "c:\users\hbw33\agilecoder\ui\src\agilecoder\agilecoder\run_api.py", line 10, in <module>
    from agilecoder.components.chat_chain import ChatChain
  File "c:\users\hbw33\agilecoder\ui\src\agilecoder\agilecoder\components\chat_chain.py", line 12, in <module>
    from agilecoder.components.chat_env import ChatEnv, ChatEnvConfig
  File "c:\users\hbw33\agilecoder\ui\src\agilecoder\agilecoder\components\chat_env.py", line 14, in <module>
    from agilecoder.components.documents import Documents
  File "c:\users\hbw33\agilecoder\ui\src\agilecoder\agilecoder\components\documents.py", line 7, in <module>
    from project import ProjectManager
ModuleNotFoundError: No module named 'project'

**Comment by sexy-yume** [comment]
C:\Users\hbw33\AgileCoder\ui>agilecoder_ui.py
24.11.04 02:44:05: root: INFO   : Initializing Devika...
24.11.04 02:44:05: root: INFO   : Initializing Prerequisites Jobs...
Traceback (most recent call last):
  File "C:\Users\hbw33\AgileCoder\ui\agilecoder_ui.py", line 24, in <module>
    from src.agents import Agent
  File "C:\Users\hbw33\AgileCoder\ui\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "C:\Users\hbw33\AgileCoder\ui\src\agents\agent.py", line 18, in <module>
    from agilecoder.camel.typing import ModelType
  File "C:\Users\hbw33\AgileCoder\ui\src\AgileCoder\agilecoder\__init__.py", line 1, in <module>
    from .cli import main
  File "C:\Users\hbw33\AgileCoder\ui\src\AgileCoder\agilecoder\cli.py", line 3, in <module>
    from agilecoder.run_api import run_task
  File "C:\Users\hbw33\AgileCoder\ui\src\AgileCoder\agilecoder\run_api.py", line 10, in <module>
    from agilecoder.components.chat_chain import ChatChain
  File "C:\Users\hbw33\AgileCoder\ui\src\AgileCoder\agilecoder\components\chat_chain.py", line 12, in <module>
    from agilecoder.components.chat_env import ChatEnv, ChatEnvConfig
  File "C:\Users\hbw33\AgileCoder\ui\src\AgileCoder\agilecoder\components\chat_env.py", line 52, in <module>
    class ChatEnv:
  File "C:\Users\hbw33\AgileCoder\ui\src\AgileCoder\agilecoder\components\chat_env.py", line 101, in ChatEnv
    def exist_bugs(self) -> tuple[bool, str]:
TypeError: 'type' object is not subscriptable

**Comment by phanchauthang** [comment]
Hi @sexy-yume 

The error might be related to a Windows issue. You could try using Linux for the UI instead.
