### ISSUE TITLE
/home/steph/Projects/AgileCoder/agilecoder/components/phase.py", line 437, in extract_pl_framework_text     text = match.group(1).strip()

### ISSUE THREAD

**Issue by svanschalkwyk** [FSoft-AI4Code/AgileCoder#5]
(agile_coder) steph@lucy:~/Projects$ agilecoder --task "Create a Caro game in Python"
------------------------------
Traceback (most recent call last):
  File "/home/steph/miniconda3/envs/agile_coder/bin/agilecoder", line 33, in <module>
    sys.exit(load_entry_point('agilecoder', 'console_scripts', 'agilecoder')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steph/Projects/AgileCoder/agilecoder/cli.py", line 24, in main
    run_task(args)                                           
    ^^^^^^^^^^^^^^
  File "/home/steph/Projects/AgileCoder/agilecoder/run_api.py", line 114, in run_task
    chat_chain.execute_chain()
  File "/home/steph/Projects/AgileCoder/agilecoder/components/chat_chain.py", line 165, in execute_chain
    self.execute_step(phase_item)
  File "/home/steph/Projects/AgileCoder/agilecoder/components/chat_chain.py", line 135, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steph/Projects/AgileCoder/agilecoder/components/phase.py", line 322, in execute
    chat_env = self.update_chat_env(chat_env)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steph/Projects/AgileCoder/agilecoder/components/phase.py", line 355, in update_chat_env
    programming_languages = extract_pl_framework_text(self.seminar_conclusion, "Programming languages").strip()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steph/Projects/AgileCoder/agilecoder/components/phase.py", line 437, in extract_pl_framework_text
    text = match.group(1).strip()
           ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by minhngh** [comment]
Hi [svanschalkwyk](https://github.com/svanschalkwyk),

Thank you for your feedback. 
This bug seems quite weird as we have never encountered it before. There are some ways you can try:
* Create a new environment and reinstall the library
* You can rerun to check whether this bug is still permanent. If you constantly encounter this error, I guess that there is an issue with the installation.
If the ways above aren't effective, please provide more details about this run, including model, agilecoder version, OS.
